In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Telco-Customer-Churn.csv")
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [3]:
df.drop('customerID', axis=1, inplace=True)
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
df['MonthlyCharges'] = pd.to_numeric(df['MonthlyCharges'], errors='coerce')
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

In [7]:
df.isnull().sum()

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [6]:
df.dropna(inplace=True)

In [8]:
df['Churn'] = df['Churn'].map({'Yes':1,'No':0})

In [9]:
df = pd.get_dummies(df, drop_first=True)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 31 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   SeniorCitizen                          7032 non-null   int64
 1   tenure                                 7032 non-null   int64
 2   MonthlyCharges                         7032 non-null   float64
 3   TotalCharges                           7032 non-null   float64
 4   Churn                                  7032 non-null   int64
 5   gender_Male                            7032 non-null   bool
 6   Partner_Yes                            7032 non-null   bool
 7   Dependents_Yes                         7032 non-null   bool
 8   PhoneService_Yes                       7032 non-null   bool
 9   MultipleLines_No phone service         7032 non-null   bool
 10  MultipleLines_Yes                      7032 non-null   bool
 11  InternetService_Fiber optic            7032 non-null   bool
 12  InternetService_No                     7032 non-null   bool
 13  OnlineSecurity_No internet service     7032 non-null   bool
 14  OnlineSecurity_Yes                     7032 non-null   bool
 15  OnlineBackup_No internet service       7032 non-null   bool
 16  OnlineBackup_Yes                       7032 non-null   bool
 17  DeviceProtection_No internet service   7032 non-null   bool
 18  DeviceProtection_Yes                   7032 non-null   bool
 19  TechSupport_No internet service        7032 non-null   bool
 20  TechSupport_Yes                        7032 non-null   bool
 21  StreamingTV_No internet service        7032 non-null   bool
 22  StreamingTV_Yes                        7032 non-null   bool
 23  StreamingMovies_No internet service    7032 non-null   bool
 24  StreamingMovies_Yes                    7032 non-null   bool
 25  Contract_One year                      7032 non-null   bool
 26  Contract_Two year                      7032 non-null   bool
 27  PaperlessBilling_Yes                   7032 non-null   bool
 28  PaymentMethod_Credit card (automatic)  7032 non-null   bool
 29  PaymentMethod_Electronic check         7032 non-null   bool
 30  PaymentMethod_Mailed check             7032 non-null   bool
dtypes: bool(26), float64(2), int64(3)
memory usage: 508.2 KB